### ISSUE TITLE
404 - File Not Found!

### ISSUE THREAD

**Issue by eshaanized** [Snigdha-OS/Snigdha-OS.github.io#13]
The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL as well as any file permissions.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.

[GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)

**Comment by eshanized** [comment]
on fix 🌮
