### ISSUE TITLE
Building Error!

### ISSUE THREAD

**Issue by iconized** [Snigdha-OS/Snigdha-OS.github.io#6]
### What is your Hugo Extended Version

0.125.1-1

### What is your Go Version

2:1.22.2-1

### What is your Node.js Version

21.7.3-1

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

Should Run Without Any Error

### Steps to Reproduce

```npm
npm run dev
```

### Code Reproduction URL

https://github.com/Snigdha-OS/Snigdha-OS.github.io

### Additional Information

> hugoplate@1.13.3 dev
> hugo server

Watching for changes in /home/icon/GitHub/Snigdha-OS.github.io/{assets,content,data,hugo_stats.json,i18n,package.json,postcss.config.js,tailwind.config.js,themes}
Watching for config changes in /home/icon/GitHub/Snigdha-OS.github.io/hugo.toml, /home/icon/GitHub/Snigdha-OS.github.io/config/_default, /home/icon/GitHub/Snigdha-OS.github.io/go.mod
Start building sites … 
hugo v0.125.1+extended linux/amd64 BuildDate=unknown

ERROR render of "404" failed: "/home/icon/GitHub/Snigdha-OS.github.io/themes/hugoplate/layouts/_default/baseof.html:11:7": execute of template failed: template: 404.html:11:7: executing "404.html" at <partial "essentials/head.html" .>: error calling partial: "/home/icon/GitHub/Snigdha-OS.github.io/themes/hugoplate/layouts/partials/essentials/head.html:12:3": execute of template failed: template: partials/essentials/head.html:12:3: executing "partials/essentials/head.html" at <partialCached "favicon" .>: error calling partialCached: "/home/icon/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/gethugothemes/hugo-modules/images@v0.0.0-20240331035203-6c6ca12add7d/layouts/partials/favicon.html:17:25": execute of template failed: template: partials/favicon.html:17:25: executing "partials/favicon.html" at <$favicon.Resize>: error calling Resize: this method is only available for raster images. To determine if an image is SVG, you can do {{ if eq .MediaType.SubType "svg" }}{{ end }}
ERROR render of "section" failed: "/home/icon/GitHub/Snigdha-OS.github.io/themes/hugoplate/layouts/_default/baseof.html:11:7": execute of template failed: template: authors/list.html:11:7: executing "authors/list.html" at <partial "essentials/head.html" .>: error calling partial: "/home/icon/GitHub/Snigdha-OS.github.io/themes/hugoplate/layouts/partials/essentials/head.html:12:3": execute of template failed: template: partials/essentials/head.html:12:3: executing "partials/essentials/head.html" at <partialCached "favicon" .>: error calling partialCached: "/home/icon/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/gethugothemes/hugo-modules/images@v0.0.0-20240331035203-6c6ca12add7d/layouts/partials/favicon.html:17:25": execute of template failed: template: partials/favicon.html:17:25: executing "partials/favicon.html" at <$favicon.Resize>: error calling Resize: this method is only available for raster images. To determine if an image is SVG, you can do {{ if eq .MediaType.SubType "svg" }}{{ end }}
ERROR render of "section" failed: "/home/icon/GitHub/Snigdha-OS.github.io/themes/hugoplate/layouts/_default/baseof.html:11:7": execute of template failed: template: about/list.html:11:7: executing "about/list.html" at <partial "essentials/head.html" .>: error calling partial: "/home/icon/GitHub/Snigdha-OS.github.io/themes/hugoplate/layouts/partials/essentials/head.html:12:3": execute of template failed: template: partials/essentials/head.html:12:3: executing "partials/essentials/head.html" at <partialCached "favicon" .>: error calling partialCached: "/home/icon/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/gethugothemes/hugo-modules/images@v0.0.0-20240331035203-6c6ca12add7d/layouts/partials/favicon.html:17:25": execute of template failed: template: partials/favicon.html:17:25: executing "partials/favicon.html" at <$favicon.Resize>: error calling Resize: this method is only available for raster images. To determine if an image is SVG, you can do {{ if eq .MediaType.SubType "svg" }}{{ end }}
ERROR render of "page" failed: "/home/icon/GitHub/Snigdha-OS.github.io/themes/hugoplate/layouts/_default/baseof.html:11:7": execute of template failed: template: authors/single.html:11:7: executing "authors/single.html" at <partial "essentials/head.html" .>: error calling partial: "/home/icon/GitHub/Snigdha-OS.github.io/themes/hugoplate/layouts/partials/essentials/head.html:12:3": execute of template failed: template: partials/essentials/head.html:12:3: executing "partials/essentials/head.html" at <partialCached "favicon" .>: error calling partialCached: "/home/icon/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/gethugothemes/hugo-modules/images@v0.0.0-20240331035203-6c6ca12add7d/layouts/partials/favicon.html:17:25": execute of template failed: template: partials/favicon.html:17:25: executing "partials/favicon.html" at <$favicon.Resize>: error calling Resize: this method is only available for raster images. To determine if an image is SVG, you can do {{ if eq .MediaType.SubType "svg" }}{{ end }}
Built in 115 ms
Error: error building site: render: failed to render pages: render of "home" failed: "/home/icon/GitHub/Snigdha-OS.github.io/themes/hugoplate/layouts/_default/baseof.html:11:7": execute of template failed: template: index.html:11:7: executing "index.html" at <partial "essentials/head.html" .>: error calling partial: "/home/icon/GitHub/Snigdha-OS.github.io/themes/hugoplate/layouts/partials/essentials/head.html:12:3": execute of template failed: template: partials/essentials/head.html:12:3: executing "partials/essentials/head.html" at <partialCached "favicon" .>: error calling partialCached: "/home/icon/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/gethugothemes/hugo-modules/images@v0.0.0-20240331035203-6c6ca12add7d/layouts/partials/favicon.html:17:25": execute of template failed: template: partials/favicon.html:17:25: executing "partials/favicon.html" at <$favicon.Resize>: error calling Resize: this method is only available for raster images. To determine if an image is SVG, you can do {{ if eq .MediaType.SubType "svg" }}{{ end }}

**Comment by eshanized** [comment]
Favicon should be `.png` file. Not `.svg`. Changed your push script as it doesn't require `--config` everytime.

**Comment by iconized** [comment]
Okay!!!
